### ISSUE TITLE
Import from stately.al

### ISSUE THREAD

**Issue by Silverow** [sonntam/node-red-contrib-xstate-machine#105]
Hi, is it possible to import from a graphics editor stately.ai? If yes, how? I'm far from programming and couldn't figure it out.

Sorry for bad english

**Comment by sonntam** [comment]
I just tried it and it seems to work correctly. What you have to know: As the docs say (which obviously no one reads 😉) the JS code within the smxstate-node should return an object of the following structure:

```js
{
    machine: xstate_machine_definition,
    config: xstate_machine_options
}
```

If you now click the export-button on statley.ai
![image](https://github.com/sonntam/node-red-contrib-xstate-machine/assets/6692408/a4ace828-78fd-4127-a4b5-c43a36f783cf)

and then choose "JavaScript" as export format you will see code that calls a `createMachine` function:
![image](https://github.com/sonntam/node-red-contrib-xstate-machine/assets/6692408/2fe6f73d-0d5f-4463-8004-8fdefc478446)

The call to createMachine has got the following structure:

```js
createMachine(xstate_machine_definition, xstate_machine_options);
```

If you just repack the two arguments into the form above it should work (the default statemachine at least works correctly for me). Here is the node's code for you for reference:
```js

/***************************
 * Main machine definition * 
 ***************************/
var xstate_machine_definition = {
  id: "Machine Name",
  initial: "Initial state",
  states: {
    "Initial state": {
      on: {
        next: {
          target: "Another state",
          internal: false,
        },
      },
    },
    "Another state": {
      on: {
        next: [
          {
            target: "Parent state",
            cond: "some condition",
            internal: false,
          },
          {
            target: "Initial state",
            internal: false,
          },
        ],
      },
    },
    "Parent state": {
      initial: "Child state",
      states: {
        "Child state": {
          on: {
            next: {
              target: "Another child state",
              internal: false,
            },
          },
        },
        "Another child state": {},
      },
      on: {
        back: {
          target: "Initial state",
          actions: {
            type: "reset",
          },
          internal: false,
        },
      },
    },
  },
  predictableActionArguments: true,
  preserveActionOrder: true,
};

/***********
 * Options *
 ***********/
var xstate_machine_options = {
    actions: {
      reset: (context, event) => { },
    },
    services: {},
    guards: {
      "some condition": (context, event) => {
        return false;
      },
    },
    delays: {},
  };
  
return {
  machine: xstate_machine_definition,
  // Configuration containing guards, actions, activities, ...
  // see above
  config: xstate_machine_options,
  // Define listeners (can be an array of functions)
  //    Functions get called on every state/context update
  listeners: (data) => {
    //node.warn(data.state + ":" + data.context.counter);
  }
};
```

![image](https://github.com/sonntam/node-red-contrib-xstate-machine/assets/6692408/a2876eef-905b-4668-8180-ed2ac75e0625)

**Comment by sonntam** [comment]
The stately.ai generated code includes calling the `createMachine()` function which in node-red is done behind the scenes out of reach of the user (which is intended in order to hide under-the-hood stuff from the user and make it easier to use). Changing this behaviour would be a breaking change that renders current node configurations invalid. So currently there is nothing planned to change the machine definition syntax in node-red.

_About using the second node output:_
You can add a custom action to a state/transition in the graphical stately.ai editor which is then added to the state machine and it's configuration object. Of course you then have to implement what the action should be doing in the javascript editor. If you want to output messages on the second output, you can use `node.send({payload: "example"});` inside the action. Example:

In the machine definition you have an entry action:

```js
{
  id: "example machine",
  initial "Initial state",
  states: {
    "Initial state": {
       entry: { type: "custom action 1" }
       ...
   }
   ...
}
```

then in the configuration object you can implement it:
```js
{
  actions: {
    "custom action 1": (context, event) => { node.send({ payload: "example" }); }
  }
}
```
